# Generated by Django 2.2.7 on 2019-12-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0003_auto_20191206_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='İsim')),
                ('comment_content', models.CharField(max_length=500, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('Seyahat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Seyahat.Seyahat', verbose_name='Makale')),
            ],
        ),
    ]
