# Generated by Django 2.2.7 on 2019-12-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seyahat', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.AlterModelOptions(
            name='seyahat',
            options={'ordering': ['-created_date']},
        ),
    ]
